### ISSUE TITLE
[遭遇] 进入 Egate 并登录后提示账号异常

### ISSUE THREAD

**Issue by KiruyaMomochi** [ShanghaitechGeekPie/Support-it-support#18]
**遭遇描述**
登录 Egate 后提示「对不起，你的账号可能存在异常哦~」

**预期行为**
正常进入 Egate。

**屏幕截图**
![image](https://user-images.githubusercontent.com/65301509/96829348-0fdb8400-146c-11eb-87ea-140d757146be.png)

**Comment by eEhyQx** [comment]
已反馈

**Comment by KiruyaMomochi** [comment]
![image](https://user-images.githubusercontent.com/65301509/96830003-3bab3980-146d-11eb-889a-7ee1a0932c2c.png)
Fixed.

**Comment by eEhyQx** [comment]
已恢复
